import Navigation from "./documentations/navigation/Navigation";
import "./globals.css";
import "@ldx/ds-css/dist/index.css";

export const metadata = {
  title: "Marius Rostad.no",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
